apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-rec-adio
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: sun-yryr/Rec-adio
