apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-rec-adio
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: sun-yryr/Rec-adio
      image: ghcr.io/sun-yryr/rec-adio-runner:0.1.0-v2.304.0
      dockerdWithinRunnerContainer: true
