# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: agqr url check

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  check:
    runs-on: self-hosted
    steps:
    -
      uses: actions/checkout@v2
      with:
        ref: 'release'
    -
      name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    -
      name: Install ffmpeg & rtmpdump
      run: |
        sudo apt update
        sudo apt install -y ffmpeg rtmpdump
    -
      name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    -
      name: Install dependencies
      run: |
        pipenv install
    -
      name: Test with unittest
      run: |
        cp 'conf/example_config.json' 'conf/config.json'
        pipenv run python -m unittest test.test_agqr
