# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: main-ci

on:
  pull_request:
    branches:
      - v3
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: self-hosted
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Check version ffmpeg & rtmpdump
      run: |
        ffmpeg -version
        rtmpdump -h 2>&1 | sed -n '1,2p'
    -
      name: Install Pipenv
      run: pip install pipenv
    -
      name: Install dependencies
      run: |
        pipenv install
    -
      name: Test with unittest
      run: |
        pipenv run test
